###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID lab2-33.eng.utah.edu)
#  Generated on:      Sat Dec  1 18:17:52 2018
#  Design:            snake_top_top
#  Command:           saveDesign DBS/snake_top_top-fplan.enc
###############################################################
current_design snake_top_top
create_clock [get_ports {clk}]  -name clk -period 20.000000 -waveform {0.000000 10.000000}
